### ISSUE TITLE
Adding plugin results in no output

### ISSUE THREAD

**Issue by mmarcuccio** [react18-tools/esbuild-plugin-remove-duplicate-imports#2]
```
  await build({
    bundle: true,
    target: 'es6',
    format: 'esm',
    entryPoints,
    outdir: './dist/esm',
    logLevel: 'info',
    plugins: [
      nodeExternalsPlugin({
        dependencies: false,
        devDependencies: false,
        peerDependencies: true,
      }),
      rdiPlugin(),
    ],
  })
```

I see the file listed in the CLI output, but afterwards no file is in the dist/esm directory.

**Comment by mayank1513** [comment]
Could you please provide us with the minimal reproducible example so that we can understand and fix the issue ASAP.

**Comment by mayank1513** [comment]
Please refer to, or create your project setup using https://github.com/react18-tools/turborepo-template/ for the best experience.

**Comment by joaquin-terrasamoya-mw** [comment]
I found [where it's being](https://github.com/react18-tools/turborepo-template/blob/main/packages/shared/tsup.config.ts) used in that repo, but it's being done with `tsup` instead of `esbuild` directly. I will try to switch `esbuild` with `tsup` to see if it works, but as @mmarcuccio mentioned, it doesn't work as of now with just `esbuild`.
